--- #YAML:1.0
name: Test-TAP-XML
version: 0.03
author:
  - Michael Peters <mpeters@plusthree.com>
abstract: Output test results as XML
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
